### PR TITLE
fix: Validate DOM nesting

### LINKED ISSUE #23: warning.js:33 Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.
```
warning.js:33 Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.
    in button (created by Title)
    in CopyToClipboard (created by Title)
    in div (created by Title)
    in Title
    in button (created by DownPanel)
    in div (created by DownPanel)
    in div (created by DownPanel)
    in DownPanel (created by Container(DownPanel))
    in Container(DownPanel) (created by Layout)
    in div (created by Layout)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by Layout)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by Layout)
    in div (created by Layout)
    in Layout (created by Container(Layout))
    in Container(Layout)
    in div
```

This happens because of nested `<button>`: 

image

image

### PR DESCRIPTION
**Pull request by samouss**
**Summary**

Fix #23 

This PR aims to fix the issue related to invalid DOM nesting. The `Copy` button has been moved from the tab to the content of the panel.

- update to the latest version of Storybook
- update the `<Title />` component, for only display the title
- update the `<JSX />` component, for display the `Copy` button
- fix the warnings inside the tests
- run prettier

**Before:**

screen shot 2017-12-03 at 16 16 29

**After:**

screen shot 2017-12-03 at 16 15 36

### CODE REVIEW

**Comment by samouss** [comment]
Any follow up on this?

**Comment by ndelangen** [comment]
Hi @samouss Sorry for the (too) late reply.

We really appreciate your effort, thank you.

How would you feel about moving the `copy` button to the lower right? Much like the `clear` button on some other panels (like actions), see here: https://storybooks-cra.netlify.com/?selectedKind=Welcome&selectedStory=to%20Storybook&full=0&down=1&left=1&panelRight=1&downPanel=storybook%2Factions%2Factions-panel

screen shot 2017-12-12 at 15 07 46

Either way, this is good to merge IMHO

**Comment by samouss** [comment]
@ndelangen I will update it ASAP thanks for the feedback!

**Comment by ndelangen** [comment]
@samouss I saw you archived your slack account on the storybook slack, If you re-join perhaps we could have a short chat?

I'm looking for people to help us with maintain this package ;)

**Comment by samouss** [comment]
I can't reactivate my account, I need an administrator manipulation to re-enable it.

> If your account was deactivated by mistake, please contact a Workspace Administrator to reactivate it.

**Comment by ndelangen** [comment]
I re-activated it manually 🎟

**Comment by samouss** [comment]
@ndelangen Should be good now!

screen shot 2017-12-12 at 18 57 14

**Comment by ndelangen** [comment]
Nice, will publish momentarily!

Thank you @samouss ! 👍

**Comment by ndelangen** [comment]
Updated some dependencies and published a new minor: `5.1.0`

**Pull request merged**
