### PR TITLE
Beautify html if template string is being displayed.

### PR DESCRIPTION
**Pull request by Alfredo-Delgado**
Options are passed through to `js-beautify.html()` if `enableBeautify` (default: true) is not disabled.

### CODE REVIEW

**Comment by ndelangen** [comment]
LGTM

**Comment by Alfredo-Delgado** [comment]
https://www.npmjs.com/~alfredo-delgado

**Comment by ndelangen** [comment]
Feel free to merge.

Are you comfortable building it locally and publishing yourself? Or would you like me to do it?

**Comment by Alfredo-Delgado** [comment]
👍 : `npm run build && npm version minor && npm publish && git push origin master`

**Comment by Alfredo-Delgado** [comment]
I forgot to `git push origin --tags`. That's been resolved, now.

**Pull request merged**
