### PR TITLE
sb4 : support the active flag

### PR DESCRIPTION
**Pull request by libetl**
We are using JSX instead of storysource in our payment component (@Egencia),
and it looks like it is not supporting the active flag yet.

Can you have a look at it ?

thank you.

### CODE REVIEW

**Comment by ndelangen** [comment]
I'm afraid this will break the addon.

If the addon panel isn't rendered, it will not receive messages from channel.
You'd need to pass the active prop down into the JSX component, and toggle it's inner render instead:
https://github.com/storybooks/addon-jsx/blob/master/src/jsx.js#L37

**Comment by wcastand** [comment]
hi, i didn't follow or contribute to storybook and his addons for a while so i'm probably not the best to valid and reviews this because i have no idea the active property. :)

**Comment by libetl** [comment]
A toute fin utile, je t'ajoute aussi @alexandrebodin

**Comment by alexandrebodin** [comment]
I don't see any issue with this. But I want @ndelangen opinion in case I'm missing sth

**Comment by ndelangen** [comment]
LGTM

**Pull request merged**
